server:
  port: 8080
spring:
  application:
    name: "CHDA2025"
  h2:
    console:
      enabled: true
      path: /h2c
  datasource:
    url: "jdbc:h2:file:./h2/prod;DB_CLOSE_ON_EXIT=FALSE"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ~
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: update
  web:
    resources:
      cache:
        period: 31536000
      chain:
        compressed: false
ukgov:
  companieshouse:
    service: "registry"
    developerName: "Federico"
    docsapp:
      test: false
      secretCode: 139
